uservariables:
    user_email: "Email"
    user_name: "Name"
    user_location: "Location for weather. Leave blank if not using caelestia shell"

config:
    backup: false
    banner: false
    create: true
    dotpath: home
    keepdot: false
    link_dotfile_default: nolink
    link_on_import: nolink
    longkey: false
    workdir: cache
    import_variables:
        - uservariables.yaml:optional
        - variables.yaml
        

dotfiles:
    d_hypr:
        src: dotfiles/hypr
        dst: ~/.config/custom-dotfiles/hypr
    d_pictures:
        src: Wallpapers
        dst: ~/Pictures/Wallpapers
        link: absolute
    d_termux:
        src: termux
        dst: ~/.termux
        link: absolute
    d_xdg-icons:
        src: theme-resources/icons
        dst: ~/.local/share/icons
        link: absolute
    d_icons:
        src: theme-resources/icons
        dst: ~/.icons
        link: absolute
    d_fonts:
        src: theme-resources/fonts
        dst: ~/.local/share/fonts
        link: absolute
        actions:
            - refresh_fonts
    d_yazi:
        src: dotfiles/yazi
        dst: ~/.config/yazi
        link: absolute
        actions:
            - create_yazi_desktop
    f_bashrc:
        src: bashrc
        dst: ~/.bashrc
    f_caelestia-hypr:
        src: dotfiles/caelestia/hypr-user.lua
        dst: ~/.config/caelestia/hypr-user.lua
    f_fish:
        src: dotfiles/fish/config.fish
        dst: "{{@@ fish_config_dir @@}}"
        link: absolute
    f_gitconfig:
        src: gitconfig
        dst: ~/.gitconfig
        link: absolute
    f_caelestia-shell:
        src: dotfiles/caelestia/shell.json
        dst: ~/.config/caelestia/shell.json
        link: absolute
    f_nvim-default:
        src: dotfiles/nvim/patch.lua
        dst: ~/.config/nvim/after/plugin/patch.lua
    f_yt-dlp:
        src: dotfiles/yt-dlp/config
        dst: ~/.config/yt-dlp/config
    f_fish-greeting:
        src: dotfiles/fish/fish_greeting.fish
        dst: ~/.config/fish/functions/fish_greeting.fish
    f_fastfetch:
        src: dotfiles/fastfetch/config.jsonc
        dst: ~/.config/fastfetch/config.jsonc
    f_starship:
        src: dotfiles/starship.toml
        dst: ~/.config/starship.toml
    f_termux-hush:
        src: hushlogin
        dst: ~/.hushlogin
    f_swappy:
        src: dotfiles/swappy/config
        dst: ~/.config/swappy/config
        link: absolute
    f_eap:
        src: dotfiles/eap/config.toml
        dst: ~/.config/eap/config.toml
    f_fontconfig:
        src: dotfiles/fontconfig/fonts.conf
        dst: ~/.config/fontconfig/fonts.conf
    f_mimeapps:
        src: dotfiles/mimeapps.list
        dst: ~/.config/mimeapps.list
    f_gtk-3:
        src: dotfiles/gtk-theming.ini
        dst: ~/.config/gtk-3.0/settings.ini
    f_gtk-4:
        src: dotfiles/gtk-theming.ini
        dst: ~/.config/gtk-4.0/settings.ini
    f_cursor-fallback:
        src: cursor-theme
        dst: ~/.icons/default/index.theme
    f_yay:
        src: dotfiles/yay/config.json
        dst: ~/.config/yay/config.json
        link: absolute
    f_eap-shells:
        src: dotfiles/eap/shells.toml
        dst: ~/.config/eap/shells.toml

actions:
    post:
        create_yazi_desktop: "[[ -f ~/.local/share/applications/yazi.desktop ]] || cat {{@@ _dotdrop_dotpath @@}}/applications/yazi.desktop > ~/.local/share/applications/yazi.desktop"
        refresh_fonts: "fc-cache -fv"

profiles:
    DobbynciCode:
        variables:
            fish_config_dir: ~/.config/caelestia/user-config.fish
        dotfiles:
            - d_hypr
            - d_pictures
            - d_icons
            - d_xdg-icons
            - d_fonts
            - d_yazi
            - f_bashrc
            - f_caelestia-hypr
            - f_fish
            - f_gitconfig
            - f_caelestia-shell
            - f_nvim-default
            - f_yt-dlp
            - f_fish-greeting
            - f_swappy
            - f_eap
            - f_starship
            - f_mimeapps
            - f_cursor-fallback
            - f_gtk-3
            - f_gtk-4
            - f_yay
            - f_fontconfig
            - f_eap-shells
    localhost:
        variables:
            fish_config_dir: ~/.config/fish/config.fish
        dotfiles:
            - d_termux
            - f_nvim-default
            - f_gitconfig
            - f_bashrc
            - f_fish
            - f_fish-greeting
            - f_fastfetch
            - f_starship
            - f_termux-hush
            - f_eap
            - f_eap-shells
    BaseArchInstall:
        variables:
            fish_config_dir: ~/.config/fish/config.fish
        dotfiles:
            - d_pictures
            - d_icons
            - d_xdg-icons
            - d_fonts
            - f_bashrc
            - f_gitconfig
            - f_fish
            - f_nvim-default
            - f_eap
            - f_mimeapps
            - f_cursor-fallback
            - f_gtk-3
            - f_gtk-4
            - f_fontconfig
            - f_eap-shells
