uservariables:
    user_email: "email"
    user_name: "name"

config:
    backup: false
    banner: false
    create: true
    dotpath: home
    keepdot: false
    link_dotfile_default: nolink
    link_on_import: nolink
    longkey: false
    workdir: cache
    import_variables:
        - variables.yaml
        - uservariables.yaml:optional

dotfiles:
    d_hypr:
        src: dotfiles/hypr
        dst: ~/.config/custom-dotfiles/hypr
    d_pictures:
        src: Wallpapers
        dst: ~/Pictures/Wallpapers
        link: absolute
    d_termux:
        src: termux
        dst: ~/.termux
        link: absolute
    f_bashrc:
        src: bashrc
        dst: ~/.bashrc
    f_caelestia-hypr:
        src: dotfiles/caelestia/hypr-user.conf
        dst: ~/.config/caelestia/hypr-user.conf
    f_fish:
        src: dotfiles/fish/config.fish
        dst: "{{@@ fish_config_dir @@}}"
        link: absolute
    f_gitconfig:
        src: gitconfig
        dst: ~/.gitconfig
        link: absolute
    f_caelestia-shell:
        src: dotfiles/caelestia/shell.json
        dst: ~/.config/caelestia/shell.json
        link: absolute
    f_nvim-default:
        src: dotfiles/nvim/patch.lua
        dst: ~/.config/nvim/after/plugin/patch.lua
    f_yt-dlp:
        src: dotfiles/yt-dlp/config
        dst: ~/.config/yt-dlp/config
    f_fish-greeting:
        src: dotfiles/fish/fish_greeting.fish
        dst: ~/.config/fish/functions/fish_greeting.fish
    f_fastfetch:
        src: dotfiles/fastfetch/config.jsonc
        dst: ~/.config/fastfetch/config.jsonc
    f_starship:
        src: dotfiles/starship.toml
        dst: ~/.config/starship.toml
    f_termux-hush:
        src: hushlogin
        dst: ~/.hushlogin

actions:
    post:
        change_shell: "chsh -s {{@@ shell @@}}"

profiles:
    DobbynciCode:
        variables:
            fish_config_dir: ~/.config/caelestia/user-config.fish
        dotfiles:
            - d_hypr
            - d_pictures
            - f_bashrc
            - f_caelestia-hypr
            - f_fish
            - f_gitconfig
            - f_caelestia-shell
            - f_nvim-default
            - f_yt-dlp
    localhost:
        variables:
            fish_config_dir: ~/.config/fish/config.fish
        actions:
            - change_shell
        dotfiles:
            - d_termux
            - f_nvim-default
            - f_gitconfig
            - f_fish
            - f_fish-greeting
            - f_fastfetch
            - f_starship
            - f_termux-hush
