config:
    backup: true
    banner: false
    create: true
    dotpath: system
    keepdot: false
    link_dotfile_default: nolink
    link_on_import: nolink
    longkey: false

dotfiles:
    f_autologin:
        src: autologin.conf
        dst: /etc/systemd/system/getty@tty1.service.d/override.conf
    f_pacman-setting:
        src: pacman.conf
        dst: /etc/pacman.conf

profiles:
    DobbynciCode:
      dotfiles:
        - f_autologin
        - f_pacman-setting
