uservariables:
    user_email: "email"
    user_name: "name"
config:
    backup: false
    banner: false
    create: true
    dotpath: home
    keepdot: false
    link_dotfile_default: nolink
    link_on_import: nolink
    longkey: false
    workdir: cache
    import_variables:
        - variables.yaml
        - uservariables.yaml:optional
dotfiles:
    # --- [ i ] - Directories ---
    d_hypr:
        src: dotfiles/hypr
        dst: ~/.config/custom-dotfiles/hypr
    d_pictures:
        src: Wallpapers
        dst: ~/Pictures/Wallpapers
        link: absolute
    # --- [ i ] - Files ---
    f_bashrc:
        src: bashrc
        dst: ~/.bashrc
    f_caelestia-hypr:
        src: dotfiles/caelestia/hypr-user.conf
        dst: ~/.config/caelestia/hypr-user.conf
    f_caelestia-fish:
        src: dotfiles/caelestia/user-config.fish
        dst: "{{@@ fish_config_dir @@}}"
        link: absolute
    f_gitconfig:
        src: gitconfig
        dst: ~/.gitconfig
        link: absolute
    f_caelestia-shell:
        src: dotfiles/caelestia/shell.json
        dst: ~/.config/caelestia/shell.json
        link: absolute
    f_nvim-default:
        src: dotfiles/nvim/patch.lua
        dst: ~/.config/nvim/after/plugin/patch.lua
    f_yt-dlp:
        src: dotfiles/yt-dlp/config
        dst: ~/.config/yt-dlp/config
profiles:
    DobbynciCode:
        variables:
            fish_config_dir: ~/.config/caelestia/user-config.fish
        dotfiles:
            # --- [ i ] - Directories ---
            - d_hypr
            - d_pictures
            # --- [ i ] - Files ---
            - f_bashrc
            - f_caelestia-hypr
            - f_caelestia-fish
            - f_gitconfig
            - f_caelestia-shell
            - f_nvim-default
            - f_yt-dlp
    localhost:
        variables:
            fish_config_dir: ~/.config/fish/config.fish
        dotfiles:
            - f_nvim-default
            - f_gitconfig
            - f_caelestia-fish
