-- --- [ i ] - No-U (Unbinds) -
hl.unbind("SUPER + S")
hl.unbind("CTRL_SHIFT + Escape")
hl.unbind("SUPER + M")
hl.unbind("SUPER + D")
hl.unbind("SUPER + R")
hl.unbind("SUPER + W")
hl.unbind("SUPER + E")
hl.unbind("SUPER_ALT + Space")
hl.unbind("SUPER + SUPER_L")
hl.unbind("SUPER + left")
hl.unbind("SUPER + right")
hl.unbind("SUPER + up")
hl.unbind("SUPER + down")
hl.unbind("SUPER + F")
hl.unbind("SUPER + L")
hl.unbind("SUPER + Space")
hl.unbind("SUPER + C")
