{%@@ if profile != "localhost" @@%}
if [ -z "$WAYLAND_DISPLAY" ] && [ "$XDG_VTNR" -eq 1 ]; then
	exec start-hyprland
fi
{%@@ endif @@%}
{%@@ if profile == "localhost" @@%}
alias apt="nala"
alias rld="source ~/.bashrc"
{%@@ endif @@%}

alias ls='ls --color=auto'
alias grep='grep --color=auto'
PS1='[\u@\h \W]\$ '

export PATH="$PATH:$HOME/.local/bin"

if [[ $- == *i* ]]; then
    exec {{@@ interactive_shell @@}}
fi

