[options]
HoldPkg                     = pacman glibc
Architecture                = auto
IgnorePkg                   =
IgnoreGroup                 =
NoUpgrade                   =
NoExtract                   =
ParallelDownloads           = 10
DownloadUser                = alpm
SigLevel                    = Required DatabaseOptional
LocalFileSigLevel           = Optional
CheckSpace
Color
ILoveCandy
VerbosePkgLists

[core]
Include                     = /etc/pacman.d/mirrorlist

[extra]
Include                     = /etc/pacman.d/mirrorlist

[multilib]
Include                     = /etc/pacman.d/mirrorlist
