$source_dir = ~/.config/custom-dotfiles/hypr/modules

$UI = $source_dir/ui
$UX = $source_dir/ux

$mainMod = SUPER

$terminal = {{@@ terminal @@}}
$browser = {{@@ browser @@}}
$file_manager = {{@@ file_manager @@}}
$volume_control = {{@@ volume_control @@}}
