$source_dir = ~/.config/custom-dotfiles/hypr/modules

$UI = $source_dir/ui
$UX = $source_dir/ux

$mainMod = SUPER

$terminal = foot
$browser = brave
$file_manager = foot -a yazi-float yazi
$volume_control = pavucontrol
